homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 377
  unit_system: imperial
  time_zone: America/Phoenix
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.50.0/24
        - fd00::/8
frontend:
config:
system_health:
hacs:
  token: dae23764f92a84ac50d214b0a78a437979719aee
#custom_updater:
#  track:
#    - components
#    - python_scripts
#  component_urls:
#    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
#    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
#  python_script_urls:
#    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
http:
discovery:
conversation:
history:
logbook:
map:
sun:
cloud:

fastdotcom:
  scan_interval:
      minutes: 30
      
# Sensors
sensor:
  # Weather prediction
  - platform: yr
  #Bruh Multisensor Parts
  - platform: mqtt  
    state_topic: "bruh/sensornode1"  
    name: "SN1 Humidity"  
    unit_of_measurement: "%"  
    value_template: '{{ value_json.humidity | round(1) }}'  
  - platform: mqtt  
    state_topic: "bruh/sensornode1"  
    name: "SN1 LDR"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"  
    value_template: '{{ value_json.ldr }}'  
  - platform: mqtt  
    state_topic: "bruh/sensornode1"  
    name: "SN1 PIR"  
    value_template: '{{ value_json.motion }}'  
  - platform: mqtt  
    state_topic: "bruh/sensornode1"  
    name: "SN1 Temperature"  
    unit_of_measurement: "째F"  
    value_template: '{{ value_json.temperature | round(1) }}'  
  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "SN1 Real Feel"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt  
    state_topic: "bruh/sensornode2"  
    name: "SN2 Humidity"  
    unit_of_measurement: "%"  
    value_template: '{{ value_json.humidity | round(1) }}'  
  - platform: mqtt  
    state_topic: "bruh/sensornode2"  
    name: "SN2 LDR"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"  
    value_template: '{{ value_json.ldr }}'  
  - platform: mqtt  
    state_topic: "bruh/sensornode2"  
    name: "SN2 PIR"  
    value_template: '{{ value_json.motion }}'  
  - platform: mqtt  
    state_topic: "bruh/sensornode2"  
    name: "SN2 Temperature"  
    unit_of_measurement: "째F"  
    value_template: '{{ value_json.temperature | round(1) }}'  
  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "SN2 Real Feel"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include_dir_list automations
script: !include scripts.yaml

konnected: !include components/konnected.yaml
alarm_control_panel: !include components/alarm.yaml

panel_iframe:
  configurator: 
    title: Configurator 
    icon: mdi:wrench 
    url: http://192.168.50.118:8123/api/hassio_ingress/nVpz9UPGUO6kDTxxJR1TSEhwej1nnePGQg06uKPG3PE/

ifttt:
  key: !secret ifttt_key

ecobee:
  api_key: !secret ecobee_key

tplink:
  switch:
  - host: 192.168.50.180
  - host: 192.168.50.181

life360:
  # MPH, assuming imperial units.
  # If using metric (KPH), the equivalent would be 29.
  driving_speed: 18
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state: [driving, moving]
  # Set comm error thresholds so first is not logged,
  # second is logged as a WARNING, and third and fourth
  # are logged as ERRORs.
  warning_threshold: 2
  error_threshold: 3
  accounts:
    - username: !secret life360_username
      password: !secret life360_password

notify:
  - platform: html5
    name: PushNotify
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: alexa_media
    name: alexa_media

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_pw
      url: amazon.com
      exclude_devices:
      - "This Device"
      - "Michael's Fire"
      - "Michael's 2nd Fire"
      - "Michael's 3rd Fire"
      - "Michael's 4th Fire"
      - "Michael's Alexa Apps"
      - "Haylee's Alexa Apps"
      - "Haylee's 2nd Fire"
      - "My Dash"

mqtt:  
  broker: 192.168.50.118  
  port: 1883  
  client_id: home-assistant-1  
  username: "mqtt"  
  password: "mqtt"  

light:  
  - platform: limitlessled
    bridges:
    - host: 192.168.50.182
      groups:
      - number: 1
        type: white
        name: KitchenLED1
      - number: 2
        type: white
        name: KitchenLED2
#      - number: 3
#        type: white
#        name: KitchenLED3
#      - number: 4
#        type: white
#        name: KitchenLED4
  - platform: mqtt
    schema: json
    name: "SN1 LED"  
    state_topic: "bruh/sensornode1"  
    command_topic: "bruh/sensornode1/set"  
    brightness: true  
    effect: true
    effect_list: [flash] 
    rgb: true
    optimistic: false  
    qos: 0
  - platform: mqtt
    schema: json
    name: "SN2 LED"  
    state_topic: "bruh/sensornode2"  
    command_topic: "bruh/sensornode2/set"  
    brightness: true  
    effect: true
    effect_list: [flash] 
    rgb: true
    optimistic: false  
    qos: 0

switch:
  - platform: broadlink
    host: 192.168.50.183
    mac: !secret broadlinkMac

#introduction:
#roku:
#logger:
#  default: info