alias: AlexaState
trigger:
- entity_id: binary_sensor.garage_door
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.house_to_garage_door
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.exterior_garage_door
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.front_door
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.great_room_windows
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.living_room_windows
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.master_bedroom_window
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.middle_bedroom_window
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.office_bedroom_window
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.sliding_back_door
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.street_bedroom
  platform: state
  from: 'off'
  to: 'on'
- entity_id: binary_sensor.swinging_back_door
  platform: state
  from: 'off'
  to: 'on'
condition: []
action:
- service: notify.alexa_media
  data_template:
    data:
      type: announce
    target: media_player.michaels_ecobee4
    message: ' {{trigger.to_state.attributes.friendly_name}} was opened. '